export type TEquipment = {
  status: string;
  NomeEntidade: string;
  numFistel: string;
  numAto: string;
  numEstacao: string;
  enderecoEstacao: string;
  endComplemento: string;
  siglaUf: string;
  codMunicipio: string;
  designacaoEmissao: string;
  tecnologia: string;
  tipoTecnologia: string;
  meioAcesso: string;
  freqTxMHz: string;
  freqRxMHz: string;
  azimute: string;
  codTipoClasseEstacao: string;
  classInfraFisica: string;
  compartilhamentoInfraFisica: string;
  codTipoAntena: string;
  codEquipamentoAntena: string;
  ganhoAntena: string;
  frenteCostaAntena: string;
  anguloMeiaPotenciaAntena: string;
  anguloElevacao: string;
  polarizacao: string;
  AlturaAntena: string;
  codEquipamentoTransmissor: string;
  potenciaTransmissorWatts: string;
  latitude: string;
  longitude: string;
  lodDebitoTFI: string;
  dataLicenciamento: string;
  DataPrimeiroLicenciamento: string;
  numRede: string;
  _id: string;
  dataValidade: string;
  numFistelAssociado: string;
  nomeEntidadeAssociado: string;
};

export interface IEquipmentStates {
  labels: string[];
  equipamentos: TEquipment[];
  equipamento: TEquipment | null;
  error: boolean;
  success: boolean;
  loading: boolean;
  message: string;
  page: number;
  pageCount: number;
}
